[project]
name = "gomoku-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "solkaze", email = "solkaze.arch.tech@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "notebook>=7.6.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
]

[project.scripts]
gomoku-ai = "gomoku_ai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
